### ISSUE TITLE
Zeekea v1.6.1: Client Crash when breaking or right-clicking a Torch Lamp

### ISSUE THREAD

**Issue by RogueRaiden** [ZigTheHedge/vsmods#8]
Place Torch Lamp, add torches, right-click lamp or breaking it crashes the client out, and does not crash the server.

Game Version: v1.16.3 (Stable)
Loaded Mods: cats@1.3.0, emotemenu@1.0.4, fancydoors@1.1.0, instruments@1.1.1, meteoricexpansion@1.0.6, leadroof@1.1.0, necessaries@1.1.1, petai@1.3.2, quieterevil@1.0.0, quietermusic@0.1.0, targetDot@1.0.3, game@1.16.3, wolftaming@1.3.0, zeekea@1.6.0, carrycapacity@0.6.4, deathwaypoints@1.0.3, hudclock@2.7.0, creative@1.16.3, survival@1.16.3, xlib@0.6.8, doffanddonagain@2.0.0, xskills@0.6.8, rhserveradditions@0.1.1
2/7/2022 4:06:50 PM: Critical error occurred
System.Exception: Can't create itemstack without block!
   at Vintagestory.API.Common.ItemStack..ctor(Block block, Int32 stacksize)
   at zeekea.src.torchlamp.TorchLamp.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel)
   at zeekea.src.DummyUP.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _TcPKe0ld0EAbHR8YsMG1OLy9q8O._vg1QFi5yvtdWtcWdYGzwV9j9PVf(Single )
   at _SbWHHe8Ad6lBV8IRbvWFqut7ren._mSnyaJUIQhBb8A1j3UUn7uh5BBO(Single )
   at _SbWHHe8Ad6lBV8IRbvWFqut7ren._b365Cpnna1p8GSaDyyO3EH2VfOD(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _muFH2BhSjNKo8GSc2o33Nm6Ckup._SwLkq72vc0vcc3OnHXTAS19pm9p(_tVmXPdKJ3JBDWFc8tBtvgftcfhl , String[] )
   at _XL1Xa21FKJVFetNmIumId5p6UDU._SwLkq72vc0vcc3OnHXTAS19pm9p(ThreadStart )

**Comment by thejams13** [comment]
Can Confirm It happened on my server. I just went in the config and disabled the Torch Lamp. Seems to fix the issue I was able then able to go creative and destroy the now unknow block. Thanks for a great Mod.
